// Package tunnels implements the agent's native tunnel-lifecycle engine:
// one Driver per core (Backhaul, Rathole, GOST, Hysteria2, ...), registered
// by name and looked up generically by the HTTP layer -- server.go never
// branches on core type itself. Adding a future core means adding one new
// file that self-registers via init(), not editing this file or server.go.
//
// Ported from ha-tunnel-manager's core/*/core.sh (a separate, untouched
// repo) as ground truth for correct config/systemd shapes -- not by
// shelling out to it. Tunnels created here live in their own namespace
// (service names prefixed "tunnel-agent-", own config dir) so they can
// never collide with anything tunnel-manager.sh has configured on the same
// box, which stays visible read-only via the existing /api/v1/tunnels proxy.
package tunnels

import "context"

// Role is which side of a two-server tunnel this instance plays. Which
// named side ("source"/"destination") maps to which Role is a per-core, UI-
// level decision (the panel's core registry) -- not fixed here, since e.g.
// Backhaul/Rathole put the server role on the IRAN/source side while
// Hysteria2/TUIC put the forwarded-port config on the client side.
type Role string

const (
	RoleServer Role = "server"
	RoleClient Role = "client"
)

// PortMapping is one forwarded port pair, always validated as numeric
// 1-65535 on both sides (see ValidatePort) before it ever reaches a driver.
type PortMapping struct {
	Remote int `json:"remote"`
	Local  int `json:"local"`
}

// Spec is the validated, core-agnostic instruction to stand up one tunnel
// instance. Core-specific extra options belong in that core's own Driver
// implementation (reading whatever it needs off Spec/Extra), kept out of
// this shared struct so adding a core never means widening it for everyone.
type Spec struct {
	// ID is this tunnel's agent-local identity: lowercase alnum + dashes,
	// 1-48 chars (see ValidateTunnelID). Every generated file/service name
	// derives from it.
	ID     string            `json:"id"`
	Role   Role              `json:"role"`
	Port   int               `json:"port"`            // bind port (server role) -- 0 for client role
	Peer   string            `json:"peer,omitempty"`  // "host:port" of the other side -- required for client role
	Secret string            `json:"-"`               // shared token/PSK, generated by the panel orchestrator -- never logged or echoed back
	Ports  []PortMapping     `json:"ports,omitempty"` // forwarded ports, server role only
	Extra  map[string]string `json:"extra,omitempty"` // core-specific overrides (e.g. transport type)
}

// Health is the result of a real health check: process state, port
// reachability, and (where the core supports it, via systemd's
// IPAccounting) a traffic-activity signal -- not just "is the unit active".
//
// LatencyMs/Connections/ReconnectCount/CPUPercent/RAMPercent are all real,
// directly-measured signals (TCP dial timing, /proc/net/tcp, systemd's own
// NRestarts counter, /proc/<pid> sampling) -- populated by runtimeStats in
// health.go and merged in by every driver's Health(). There is deliberately
// no packet-loss field: without either raw-socket ICMP (needs CAP_NET_RAW)
// or per-core protocol support neither Backhaul/Rathole/GOST/Hysteria2
// expose, any number here would be fabricated rather than measured -- and
// this project's own conventions (see progress.go) treat a real "we don't
// know" as strictly better than a fake percentage.
type Health struct {
	Process        string  `json:"process"` // "running" | "stopped" | "unknown"
	PortOpen       bool    `json:"port_open"`
	Traffic        bool    `json:"traffic_active"`
	RxBytes        uint64  `json:"rx_bytes"`
	TxBytes        uint64  `json:"tx_bytes"`
	LatencyMs      float64 `json:"latency_ms,omitempty"`
	HasLatency     bool    `json:"has_latency"`
	Connections    int     `json:"connections"`
	ReconnectCount uint64  `json:"reconnect_count"`
	CPUPercent     float64 `json:"cpu_percent,omitempty"`
	RAMPercent     float64 `json:"ram_percent,omitempty"`
	HasProcStats   bool    `json:"has_proc_stats"`
	Detail         string  `json:"detail,omitempty"`
}

// Driver is the boundary every tunnel core implements. One instance per
// tunnel, built by a Factory from that tunnel's Spec -- not a singleton,
// since every method acts on one specific tunnel's files/service. Callers
// must hold that tunnel's lock (see Locks) for the duration of any call.
type Driver interface {
	// Install ensures the core's binary is present, downloading it if not.
	// Idempotent -- safe to call on every deploy.
	Install(ctx context.Context) error
	WriteConfig() error
	CreateService() error
	ConfigureFirewall() error
	Start(ctx context.Context) error
	Stop(ctx context.Context) error
	Restart(ctx context.Context) error
	Health(ctx context.Context) (Health, error)
	Logs(ctx context.Context, lines int) ([]string, error)
	// Remove tears down everything Install/WriteConfig/CreateService/
	// ConfigureFirewall created (config, service, firewall rule) -- used
	// both for a user-requested delete and for rollback when the other side
	// of a two-server deploy fails. Must not fail just because some of that
	// was already partially removed.
	Remove(ctx context.Context) error
}

// Factory builds a Driver for one tunnel from its Spec. Registered per core
// name via Register, normally from that core's own init().
type Factory func(spec Spec) (Driver, error)

var registry = map[string]Factory{}

// Register adds a core's Factory under name (e.g. "backhaul"). The only
// mutation point for the registry -- everything else just reads it.
func Register(name string, factory Factory) {
	registry[name] = factory
}

// New looks up a core by name and builds a Driver for spec. The only place
// in the agent's HTTP layer that ever needs to know a core name exists.
func New(core string, spec Spec) (Driver, error) {
	factory, ok := registry[core]
	if !ok {
		return nil, &UnknownCoreError{Core: core}
	}
	return factory(spec)
}

// SupportedCores returns every registered core name, used by
// /api/v1/agent/info to advertise what this agent build can actually do.
func SupportedCores() []string {
	names := make([]string, 0, len(registry))
	for name := range registry {
		names = append(names, name)
	}
	return names
}

// UnknownCoreError is returned by New for a core name with no registered
// driver -- kept as a typed error so the HTTP layer can map it to 400
// instead of a generic 500.
type UnknownCoreError struct{ Core string }

func (e *UnknownCoreError) Error() string {
	return "unknown tunnel core: " + e.Core
}
