package tunnels

import (
	"os"
	"strings"
	"testing"
)

func TestHysteria2ArchAsset(t *testing.T) {
	cases := map[string]bool{"amd64": true, "arm64": true, "386": false}
	for arch, wantOK := range cases {
		_, err := hysteria2ArchAsset(arch)
		if gotOK := err == nil; gotOK != wantOK {
			t.Errorf("hysteria2ArchAsset(%q): got ok=%v, want ok=%v (err=%v)", arch, gotOK, wantOK, err)
		}
	}
}

func TestHysteria2WriteConfigServerRole(t *testing.T) {
	SetDataDir(t.TempDir())
	defer SetDataDir("/etc/tunnel-agent")

	spec := Spec{
		ID:     "iran-germany-h2",
		Role:   RoleServer,
		Port:   36712,
		Secret: "auth-password",
	}
	driver, err := newHysteria2Driver(spec)
	if err != nil {
		t.Fatalf("newHysteria2Driver: %v", err)
	}
	hd := driver.(*hysteria2Driver)
	if err := hd.WriteConfig(); err != nil {
		t.Fatalf("WriteConfig: %v", err)
	}

	// WriteConfig should have generated a shared TLS cert as a side effect.
	if _, err := os.Stat(hd.certPath); err != nil {
		t.Errorf("expected a TLS cert to be generated at %s: %v", hd.certPath, err)
	}

	data, err := os.ReadFile(hd.configPath)
	if err != nil {
		t.Fatalf("reading generated config: %v", err)
	}
	config := string(data)
	for _, want := range []string{"listen: :36712", "auth:", "  type: password", `  password: "auth-password"`, "tls:"} {
		if !strings.Contains(config, want) {
			t.Errorf("expected config to contain %q, got:\n%s", want, config)
		}
	}
	if strings.Contains(config, "tcpForwarding:") {
		t.Errorf("server-role config should not contain tcpForwarding, got:\n%s", config)
	}
}

func TestHysteria2WriteConfigClientRole(t *testing.T) {
	SetDataDir(t.TempDir())
	defer SetDataDir("/etc/tunnel-agent")

	spec := Spec{
		ID:     "germany-side-h2",
		Role:   RoleClient,
		Peer:   "1.2.3.4:36712",
		Secret: "auth-password",
		Ports:  []PortMapping{{Remote: 22, Local: 2222}},
	}
	driver, err := newHysteria2Driver(spec)
	if err != nil {
		t.Fatalf("newHysteria2Driver: %v", err)
	}
	hd := driver.(*hysteria2Driver)
	if err := hd.WriteConfig(); err != nil {
		t.Fatalf("WriteConfig: %v", err)
	}
	data, err := os.ReadFile(hd.configPath)
	if err != nil {
		t.Fatalf("reading generated config: %v", err)
	}
	config := string(data)
	for _, want := range []string{
		`server: "1.2.3.4:36712"`,
		`auth: "auth-password"`,
		"insecure: true",
		"tcpForwarding:",
		"- listen: 0.0.0.0:2222",
		"remote: 127.0.0.1:22",
	} {
		if !strings.Contains(config, want) {
			t.Errorf("expected config to contain %q, got:\n%s", want, config)
		}
	}
	// The client never needs the server's certificate -- no cert should be
	// generated by a client-role WriteConfig.
	if _, err := os.Stat(hd.certPath); err == nil {
		t.Error("did not expect a TLS cert to be generated for a client-role tunnel")
	}
}
